config/routes.rb
Rails.application.routes.draw do

  # get 'shop/index'

  devise_for :users, path: 'account', controllers: { sessions: 'users/sessions' }
  devise_for :admin#, controllers: { sessions: 'admin/sessions' }

  root to: "shop#index"

  resources :admin, only: :index
  namespace :admin do
    resources :goods
    resources :orders, only: :index do
      get :change_state
    end
    resources :categories
    resources :users do
      collection do
        get 'diactivate'
        get 'activate'
      end
    end
  end
  get '/category',          to: 'shop#category'
  get '/goods/:id',         to: 'shop#show'
  get '/categories',        to: 'shop#categories'
  get '/change_currency',   to: 'shop#change_currency'
  get 'admin/update_costs', to: 'admin#update_costs'
  post '/add_to_cart',      to: 'shop#add_to_cart'


  resources :cart, only: [:index, :update] do 
    patch :recalculate, on: :collection
    get :checkout, on: :collection
    patch :order
  end

  resources :cart_item, only: :destroy, defaults: { format: 'js' }

  resources :goods
  namespace :users do
    get :account
    get :addresses
    get :orders
    get :change_account
    patch :update_account
  end
  
end

app/views/partials/_account_sidebar.html.slim
.col-md-3.left-menu
  div
    ul.nav.nav-list
      = active_link_to(t('.account'), users_account_path, :active => :exclusive, :wrap_tag => :li)
      = active_link_to(t('.addresses'), users_addresses_path, :active => :exclusive, :wrap_tag => :li)
      = active_link_to(t('.orders'), users_orders_path, :active => :exclusive, :wrap_tag => :li)

app/views/partials/_admin_header.html.slim
.navbar.navbar-default.navbar-static-top
  .container
    = link_to "Shop", admin_index_path, html_options = {class:"navbar-brand"}

app/views/partials/_users_header.html.slim
.header
  nav.navbar.container
    .navbar-header
      a.navbar-brand href='/' 
        img alt='Shop' src='/img/logo.png'
        | Shop
    .navbar-collapse.collapse.navbar-right
      ul.nav.navbar-nav
        - if current_user
          li.active
            = link_to current_user.email, user_path(current_user)
        - else
          li.active
            = link_to "Login/Register", new_user_session_path
      ul.nav.navbar-right.cart
        li.dropdown
          a href=cart_index_path
            - if @cart
              span.cart_total.cart_price value=@cart.total
                = @cart.total