config/routes.rb
Rails.application.routes.draw do

  # get 'shop/index'

  devise_for :users, path: 'account', controllers: { sessions: 'users/sessions' }
  devise_for :admin#, controllers: { sessions: 'admin/sessions' }

  root to: "shop#index"

  resources :admin, only: :index
  namespace :admin do
    resources :goods
    resources :orders, only: :index do
      get :change_state
    end
    resources :categories
    resources :users do
      collection do
        get 'diactivate'
        get 'activate'
      end
    end
  end
  get '/category',          to: 'shop#category'
  get '/goods/:id',         to: 'shop#show'
  get '/categories',        to: 'shop#categories'
  get '/change_currency',   to: 'shop#change_currency'
  get 'admin/update_costs', to: 'admin#update_costs'
  post '/add_to_cart',      to: 'shop#add_to_cart'


  resources :cart, only: [:index, :update] do 
    patch :recalculate, on: :collection
    get :checkout, on: :collection
    patch :order
  end

  resources :cart_item, only: :destroy, defaults: { format: 'js' }

  resources :goods
  namespace :users do
    get :account
    get :addresses
    get :orders
    get :change_account
    patch :update_account
  end
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  phone                  :string(255)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :email
  
  has_many :addresses
  has_many :carts
  has_many :orders
  
  attr_accessor :temp_password
  before_update :update_user

  def update_user
    self.password = self.temp_password unless self.temp_password.blank?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  
  before_filter :get_user, only: [:edit, :update, :show, :diactivate, :activate, :destroy]

  def index
    @users = User.all    
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to admin_users_url, alert: t('controllers.users.successfully_updated') }
        format.json { render action: 'index', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

  end

  def diactivate
    
  end

  def activate
    
  end

  protected
    def user
      @user
    end

    def get_user
      @user = User.find_by(id: params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :temp_password)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_action_callback :authenticate_user!, only: [:new, :create]

  def new
    super
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer || root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def account
  end

  def addresses
    @addresses = current_user.addresses
  end

  def change_account
    @user = current_user
  end

  def update_account
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to users_account_url }
      else
        format.html {}
      end
    end
  end

  def orders
    @orders = current_user.orders
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.slim
= render 'partials/account_sidebar'
.col-md-9.product
  .col-md-4
    br
    blockquote
      .row
        .pull-left = t('.email')
        .pull-right = current_user.email
      .row
        .pull-left = t('.name')
        .pull-right = current_user.name
      .row
        .pull-left = t('.phone')
        .pull-right = current_user.phone
  .change-profile
    .pull-right.btn.btn-default = link_to t('.change_btn'), users_change_account_path

app/views/users/addresses.html.slim
= render 'partials/account_sidebar'
.col-md-9.product
  - if @addresses.empty?
    .no-records
      h1 = t('no_records')
  - else
    = render 'addresses/list'

app/views/users/change_account.html.slim
= render 'partials/account_sidebar'
.col-md-9.product
  h2 Change Profile
  .col-md-5
    = semantic_form_for @user, url: users_update_account_path do |f|
      = f.inputs do
        = f.input :name, label: false, input_html: { placeholder: t('.name') }
        = f.input :phone, label: false, input_html: { placeholder: t('.phone') }

      p
        = f.actions do
          = f.action :submit, button_html: { class: 'btn pull-left' }

app/views/users/orders.html.slim
= render 'partials/account_sidebar'
.col-md-9.product
  - if @orders.empty?
    .no-records
      h1 = t('no_records')
  - else
    = render 'orders/list'
  