config/routes.rb
Rails.application.routes.draw do

  # get 'shop/index'

  devise_for :users, path: 'account', controllers: { sessions: 'users/sessions' }
  devise_for :admin#, controllers: { sessions: 'admin/sessions' }

  root to: "shop#index"

  resources :admin, only: :index
  namespace :admin do
    resources :goods
    resources :orders, only: :index do
      get :change_state
    end
    resources :categories
    resources :users do
      collection do
        get 'diactivate'
        get 'activate'
      end
    end
  end
  get '/category',          to: 'shop#category'
  get '/goods/:id',         to: 'shop#show'
  get '/categories',        to: 'shop#categories'
  get '/change_currency',   to: 'shop#change_currency'
  get 'admin/update_costs', to: 'admin#update_costs'
  post '/add_to_cart',      to: 'shop#add_to_cart'


  resources :cart, only: [:index, :update] do 
    patch :recalculate, on: :collection
    get :checkout, on: :collection
    patch :order
  end

  resources :cart_item, only: :destroy, defaults: { format: 'js' }

  resources :goods
  namespace :users do
    get :account
    get :addresses
    get :orders
    get :change_account
    patch :update_account
  end
  
end

app/models/good.rb
# == Schema Information
#
# Table name: goods
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :string(255)
#  cost_usd     :decimal(8, 2)    default(0.0)
#  created_at   :datetime
#  updated_at   :datetime
#  is_available :boolean          default(TRUE)
#  cost_eur     :decimal(8, 2)    default(0.0)
#  cost_byn     :decimal(8, 2)    default(0.0)
#

class Good < ActiveRecord::Base
  validates_presence_of :cost_usd#, :cost_eur, :cost_byn
  validates :cost_usd, numericality: { greater_than_or_equal_to: 0.01, message: "Can't believe in this cost" }
  # validates :cost_eur, numericality: { greater_than_or_equal_to: 0.01, message: "Can't believe in this cost" }
  # validates :cost_byn, numericality: { greater_than_or_equal_to: 0.01, message: "Can't believe in this cost" }
  validates_presence_of :name
  validates_presence_of :description

  has_many :good_categories
  has_many :categories, through: :good_categories
  has_many :photos
  accepts_nested_attributes_for :photos, :reject_if => :all_blank, :allow_destroy => true
  has_many :cart_items

  scope :available, -> { where(is_available: true) }

  before_save :set_all_categories

  def set_all_categories
    self.category_ids = self.all_categories
  end

  def all_categories
    (self.categories.map(&:parent_ids) + self.category_ids).flatten.uniq
  end

  def price(currency='USD')
    case currency
    when 'USD'
      self.cost_usd.to_f
    when 'EUR'
      self.cost_eur.to_f
    when 'BY'
      self.cost_byn.to_f
    else
      self.cost_usd.to_f
    end
  end
end

app/controllers/admin/goods_controller.rb
class Admin::GoodsController < AdminController
  before_filter :get_good, only: [:show, :edit, :update, :destroy]

  def index
    @goods = Good.all
  end

  def new
    @good = Good.new
    @good.photos.new
  end

  def create
    @good = Good.new(good_params)
    respond_to do |format|
      if @good.save
        format.html { redirect_to admin_goods_url, alert: t('controllers.goods.successfully_created') }
        format.json { render action: 'index', status: :created, location: @good }
      else
        format.html { render action: 'new' }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @good.update_attributes(good_params)
        format.html { redirect_to admin_goods_url, alert: t('controllers.goods.successfully_updated') }
        format.json { render action: 'index', status: :updated, location: @good }
      else
        format.html { render action: 'edit' }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    good.destroy
    respond_to do |format|
      format.html { redirect_to admin_goods_url, notice: t('controllers.goods.successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  protected

  def good
    @good
  end

  def get_good
    @good = Good.find_by(id:params[:id])
  end

  def good_params
    params.require(:good).permit( :name, :description, :cost_usd, :cost_eur, :cost_byn, :is_available, category_ids: [], photos_attributes: [:id, :avatar, :description, :_destroy] )
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
  def price_helper(cost, currency='usd')
    case currency
    when 'usd'
      number_to_currency(cost, precision:2, delimiter:" ")
    when 'eur'
      number_to_currency(cost, :unit => '&euro;'.html_safe, precision:2, delimiter:" ", format:"%u %n")
    when 'byn'
      number_to_currency(cost, unit: "Br", precision:2, delimiter:" ", format:"%n %u")
    else
      number_to_currency(cost, precision:2, delimiter:" ")
    end
  end
end

app/views/admin/goods/_form.html.slim
.input-group
  = semantic_form_for good, :url => url do |f|
    = f.inputs do
      = f.input :is_available, :label => ""
      = f.input :name
      = f.input :description, :as => :text, :input_html => { :rows => 10, :cols => 20 }
      = label_tag t('goods.form.cost')
      = " "
      a.btn#undo_auto_paste_costs
        i.icon-remove
      .input-group
        = number_field_tag 'good_cost_usd', @good.cost_usd, class: 'form-control costs-input', step:'0.01', name:'good[cost_usd]'
        span.input-group-addon style="border-radius: 0px;" = ("&nbsp;$").html_safe
      .input-group
        = number_field_tag 'good_cost_eur', @good.cost_eur, class: 'form-control costs-input', step:'0.01', name:'good[cost_eur]'
        span.input-group-addon style="border-radius: 0px;" = ("&nbsp;&euro;").html_safe
      .input-group
        = number_field_tag 'good_cost_byn', @good.cost_byn, class: 'form-control costs-input', step:'100', name:'good[cost_byn]'
        span.input-group-addon style="border-radius: 0px;" = ("Br").html_safe
      = f.input :categories, :as => :check_boxes, :collection => collection
      h3 =t('photos.form.title') 
      = f.semantic_fields_for :photos do |photo|
        = render 'photo_fields', :f => photo
      p
      a.btn#add_photo
        =t('photos.form.add_photo')
    p
    = f.actions do
      = f.action :submit, :as => :button

app/views/admin/goods/_photo_fields.html.slim
.nested-fields.photo_fields
  a.remove_photo
    i.icon-remove
  = f.inputs do
    = f.input :avatar, :as => :file, :label => false
    = f.input :description

app/views/admin/goods/edit.html.slim
.container 
  h2 =t('goods.form.edit')
  = render 'form', good: @good, url: admin_good_path, collection: Category.print_categories_with_breadcrumb(@good)

app/views/admin/goods/index.html.slim
p
.container
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading
          .row
            .col-md-6 = t('goods.index.title')
            .col-md-2.pull-right 
              a.btn href= new_admin_good_path 
                i.glyphicon-plus 
                = t('goods.index.buttons.new')

      table.table.table-hover
        thead
          tr
            th = t('goods.index.table.id')
            th
            th = t('goods.index.table.name')
            th = t('goods.index.table.cost')
            th = t('goods.index.table.categories')
            th = t('goods.index.table.availability')
            th = t('goods.index.table.actions')
        tbody
          -@goods.each do |good|
            tr
              th = link_to good.id, admin_good_path(good)
              th = image_tag(good.photos.first.avatar.url(:small)) unless good.photos.empty?
              th = good.name
              th 
                = ('%.2f' % good.cost_usd.to_f + " $").html_safe
                br
                = ('%.2f' % good.cost_eur.to_f + " &euro;").html_safe
                br
                = '%.2f' % good.cost_byn.to_f + " Br"
              th 
                -if !good.categories.empty?
                  -good.categories.each do |c|
                    .
                      =link_to c.name, admin_category_path(c) 
                -else
                  = "-"
              th =good.is_available?                
              th 
                a.btn href= edit_admin_good_path(good)
                  i.icon-pencil
                  =t('buttons.edit')
                a.btn href= admin_good_path(good) data-method='delete'
                  i.icon-trash
                  =t('buttons.delete')

app/views/admin/goods/new.html.slim
.container 
  h2 =t('goods.form.new')
  = render 'form', good: @good, url: admin_goods_path, collection: Category.print_categories_with_breadcrumb

app/views/admin/goods/show.html.slim
p
.container.show-container
  table.table.table-hover
    thead
      tr
        th
        th
    tbody
      tr
        th =t('goods.show.name')
        th = @good.name.to_s
      tr
        th = t('goods.show.description')
        th = @good.description.to_s
      tr
        th = t('goods.show.cost')
        th 
          = ('%.2f' % @good.cost_usd.to_f + " $").html_safe
          br
          = ('%.2f' % @good.cost_eur.to_f + " &euro;").html_safe
          br
          = '%.2f' % @good.cost_byn.to_f + " Br"
      tr
        th = t('goods.show.created_at')
        th = @good.created_at.to_date
      tr
        th = t('goods.show.updated_at')
        th = @good.updated_at.to_date
      - @good.photos.try(:each) do |photo|
        tr
          th = t('goods.show.photo')
          th 
            = photo.description
            = image_tag(photo.avatar.url(:medium))
  .btn-group role="group" aria-label="Buttons"
    a.btn href=admin_goods_path 
      i.icon-chevron-left
      = t('buttons.back')
    a.btn href= edit_admin_good_path(@good) 
      i.icon-pencil
      = t('buttons.edit')
  p