config/routes.rb
Rails.application.routes.draw do

  # get 'shop/index'

  devise_for :users, path: 'account', controllers: { sessions: 'users/sessions' }
  devise_for :admin#, controllers: { sessions: 'admin/sessions' }

  root to: "shop#index"

  resources :admin, only: :index
  namespace :admin do
    resources :goods
    resources :orders, only: :index do
      get :change_state
    end
    resources :categories
    resources :users do
      collection do
        get 'diactivate'
        get 'activate'
      end
    end
  end
  get '/category',          to: 'shop#category'
  get '/goods/:id',         to: 'shop#show'
  get '/categories',        to: 'shop#categories'
  get '/change_currency',   to: 'shop#change_currency'
  get 'admin/update_costs', to: 'admin#update_costs'
  post '/add_to_cart',      to: 'shop#add_to_cart'


  resources :cart, only: [:index, :update] do 
    patch :recalculate, on: :collection
    get :checkout, on: :collection
    patch :order
  end

  resources :cart_item, only: :destroy, defaults: { format: 'js' }

  resources :goods
  namespace :users do
    get :account
    get :addresses
    get :orders
    get :change_account
    patch :update_account
  end
  
end

app/views/layouts/_categories.html.slim
.col-md-3.left-menu
  div
    ul#categories
  .options
    .btn-group
      button.btn.btn-default#btn_usd
        = 'USD'
      button.btn.btn-default#btn_eur
        = 'EUR'
      button.btn.btn-default#btn_byn
        = 'BYN'

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Shop
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin/admin_application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .navbar.navbar-default.navbar-static-top
      .container
        = link_to "Shop", admin_index_path, html_options = {class:"navbar-brand"}
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to t('goods.index.title'), admin_goods_path
            li= link_to t('categories.index.title'), admin_categories_path
            li= link_to t('users.index.title'), admin_users_path
            li= link_to t('orders.index.title'), admin_orders_path
    /! show alert or notice
    .container-fluid
      - if notice
        .alert.alert-danger.alert-dismissible role="alert" 
          button.close aria-label="Close" data-dismiss="alert" type="button" 
            span aria-hidden="true"  ×
          p.notice= notice
      - elsif alert
        .alert.alert-success.alert-dismissible role="alert" 
          button.close aria-label="Close" data-dismiss="alert" type="button" 
            span aria-hidden="true"  ×
          p.alert= alert
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title Shop
    = csrf_meta_tags 
    = stylesheet_link_tag    'application', media: 'all' 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    link href='//cdnjs.cloudflare.com/ajax/libs/jstree/3.0.9/themes/default/style.min.css' rel='stylesheet'
    link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"
    script src='//cdnjs.cloudflare.com/ajax/libs/jstree/3.0.9/jstree.min.js' 
    script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"

  body
    .page-container
      .header
        nav.navbar.container
          .navbar-header
            a.navbar-brand href='/' 
              img alt='Shop' src='/img/logo.png'
              | Shop
          .navbar-collapse.collapse.navbar-right
            ul.nav.navbar-nav
              - if current_user
                li.dropdown
                  a.dropdown-toggle data-toggle="dropdown" href="#" 
                    = current_user.email
                  ul.dropdown-menu
                    li
                      = link_to t('.account'), users_account_path
                    li
                      = link_to destroy_user_session_path, :method => :delete do ||
                        i.fa.fa-sign-out.pull-right
                        = t '.logout'
              - else
                li.active
                  = link_to "Login/Register", new_user_session_path
            ul.nav.navbar-right.cart
              li.dropdown
                a href=cart_index_path
                  - if @cart
                    span.cart_total.cart_price value=@cart.total
                      = @cart.total
      .container
        .row
          = yield 

app/views/layouts/devise.html.slim
html
  head
    title
      | Shop
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .page-container
      = render partial: params[:controller] =~ /users/ ? 'partials/users_header' : 'partials/admin_header'
      .container-fluid
        - if notice
          .alert.alert-danger.alert-dismissible[role="alert"]
            button.close[type="button" data-dismiss="alert" aria-label="Close"]
              span[aria-hidden="true"]
                | ×
            p.notice
              = notice
        - elsif alert
          .alert.alert-success.alert-dismissible[role="alert"]
            button.close[type="button" data-dismiss="alert" aria-label="Close"]
              span[aria-hidden="true"]
                | ×
            p.alert
              = alert
      .container
        = yield